[project]
name = "yalunote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dynaconf>=3.2.6",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
